### ISSUE TITLE
去阴影的模型我会预计在一个礼拜后更新

### ISSUE THREAD

**Issue by GIS-Gao** [zhangbaijin/Constractive-learning-shadow-removal#10]
去阴影的模型我会预计在一个礼拜后更新

_Originally posted by @zhangbaijin in https://github.com/zhangbaijin/MemoryNet/issues/5#issuecomment-1193570316_
            
请问去阴影的模型更新了吗

**Comment by zhangbaijin** [comment]
很久没follow这个项目了，去阴影的模型可能被我弄丢了
