### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by linqwn** [zhangbaijin/Constractive-learning-shadow-removal#3]
您好，运行环境和原作者的运行环境是一样的吗？
在训练的时候是否出现了下面这种问题：
![image](https://user-images.githubusercontent.com/93809251/167246091-9e5dfe68-1ad0-4e71-95de-306066526d22.png)

**Comment by zhangbaijin** [comment]
你好，你训练的是去云的还是去阴影的

**Comment by linqwn** [comment]
是去阴影的

**Comment by zhangbaijin** [comment]
你可以改为detach().np()试试

**Comment by linqwn** [comment]
又遇到这个问题：
![image](https://user-images.githubusercontent.com/93809251/167247441-4720984a-b24a-422c-8e04-3f122cfbe533.png)

**Comment by zhangbaijin** [comment]
你是什么环境，有可能是numpy的版本问题，我自己是python 3.8,pytorch1.8,跟本来作者环境一样应该是可以跑的

**Comment by linqwn** [comment]
我试试你的环境

**Comment by zhangbaijin** [comment]
你可以去掉np，直接改为sum即可

**Comment by zhangbaijin** [comment]
你可以去掉np，直接改为sum即可

**Comment by linqwn** [comment]
这样训练的时候不会造成什么影响吗

**Comment by zhangbaijin** [comment]
应该没什么问题

**Comment by zhangbaijin** [comment]
怎么样，应该跑起来了吧
