### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Waqas\\Downloads\\Constractive-learning-shadow-removal-main\\Constractive-learning-shadow-removal-main\\Deblurring\\ MPRNet.py'

### ISSUE THREAD

**Issue by WaqasNUST** [zhangbaijin/Constractive-learning-shadow-removal#4]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Waqas\\Downloads\\Constractive-learning-shadow-removal-main\\Constractive-learning-shadow-removal-main\\Deblurring\\
MPRNet.py'

**Comment by zhangbaijin** [comment]
The project is run on the ./Deraining/  not ./Deblurring. Have you sovled the problem?
