### ISSUE TITLE
demo的model是？

### ISSUE THREAD

**Issue by aikosuzuki** [zhangbaijin/Constractive-learning-shadow-removal#5]
你好！我想直接用您train好的model来试试，但遇到了一些问题，还请指教！

To test the pre-trained models of [Decloud](https://drive.google.com/drive/folders/1hJQVQopWMD0WazeQzZC2eDbtirXkGILO?usp=sharing) on your own images, run

python demo.py --task Task_Name --input_dir path_to_images --result_dir save_images_here

这里必须指定的task，是Deblurring, Denoising和Deraining任选一个吗？它们对应的model是您提供的哪一个呢？我download下来的有三个model_best.pth, model_epoch_250_250.pth, model_latest.pth，不知该如何和这些task对应。谢谢！

**Comment by zhangbaijin** [comment]
demo的model你可以直接下载我这个项目，用的是deraining模型，这三个模型你放在一个文件夹就行，你可以选择用mobel_best的模型来进行测试，latest_model是方便断点续训的

**Comment by zhangbaijin** [comment]
注明：我去阴影的模型暂未上传，上传的是图像去云的RICE数据集的模型，后面我会把预训练模型放出来，如果需要ISTD和SRD的结果的话可以私信我

**Comment by aikosuzuki** [comment]
谢谢您的回复，我需要的正是去阴影的模型。

**Comment by zhangbaijin** [comment]
好的，应该没什么问题

**Comment by zhangbaijin** [comment]
去阴影的模型我会预计在一个礼拜后更新

**Comment by zhangbaijin** [comment]
论文已在https://arxiv.org/abs/2309.01377

**Comment by af-doom** [comment]
> 去阴影的模型我会预计在一个礼拜后更新
您好，去阴影的模型更新了吗
