### ISSUE TITLE
请问对应的论文是什么

### ISSUE THREAD

**Issue by pierowu** [zhangbaijin/Constractive-learning-shadow-removal#6]
好像没搜到本代码对应的论文

**Comment by zhangbaijin** [comment]
对的，目前还没有被接收，我也没有挂arxiv

**Comment by pierowu** [comment]
> 对的，目前还没有被接收，我也没有挂arxiv

或许可以挂一个，方便我们引用

**Comment by zhangbaijin** [comment]
好的，最近的话我会挂一个，感谢你的引用，或者你可以引用我的另一篇SpA-Former

**Comment by littlebeen** [comment]
你好，论文被接受了吗？有没有论文的链接？想要引用一下(^v^)

**Comment by zhangbaijin** [comment]
没有，太难了，审了10换个月了，人蒙了

**Comment by littlebeen** [comment]
哈哈哈我试了一下在去云上效果还是很不错的，有消息及时更新，实在不行我只能引memorynet的原文了😀

**Comment by zhangbaijin** [comment]
好的，或者你可以引用我的另一篇SpA-Former，去云效果应该是不错的， 感谢关注，欢迎加我SemiZxf

**Comment by littlebeen** [comment]
semizxf是wx吗？

**Comment by zhangbaijin** [comment]
是的

**Comment by zhangbaijin** [comment]
目前我已经挂在Arxiv了，请移步https://arxiv.org/abs/2309.01377
