### ISSUE TITLE
In MemoryNet.py, MemoryNet() forward(). How to get the x2 and x3, thif function input is x3_img

### ISSUE THREAD

**Issue by huangwenwenlili** [zhangbaijin/Constractive-learning-shadow-removal#7]

**Comment by huangwenwenlili** [comment]
def forward(self, x3_img):

        # Original-resolution Image for Stage 3
        H = x3_img.size(2)
        W = x3_img.size(3)
    
        # Multi-Patch Hierarchy: Split Image into four non-overlapping patches
        # Two Patches for Stage 2
        x2top_img  = x2[:,:,0:int(H/2),:]
        x2bot_img  = x2[:,:,int(H/2):H,:]

        x3top_img  = x3[:,:,0:int(H/2),:]
        x3bot_img  = x3[:,:,int(H/2):H,:]

**Comment by zhangbaijin** [comment]
baseline是CVPR2021的MPRNet
