### ISSUE TITLE
Increase model capacity

### ISSUE THREAD

**Issue by SysDevHayes** [zhangbaijin/Constractive-learning-shadow-removal#9]
Hi @zhangbaijin,

Thank you for your fantastic works!
I have tested your model on a customized dataset and it works very well. However, I realized two things:
1. Doing the inference on resized image yielded much better results compared to inferencing on high resolution image using sliceding window. Though, during the training, you already used random cropping. Do you have any idea on this?
2. It seems that this archecture does not work well with low-lightning images (please correct me if I'm wrong).

Additionally, I want to know if there is anyway to increase the model capacity? As well as changing the size of the receptive field?
Any guidance is priceless.
Thank you so much!

**Comment by zhangbaijin** [comment]
Thanks for your interest，
(1) The use of cropped image on training is for data enhancement
(2) Are you referring to low-light images? lol-light probably has PSNR metrics up to about 21, is increasing model capacity increasing model depth? I haven't learned about it for a while, but the current framework is learned from MPRNet.
